### ISSUE TITLE
Pipelines for labels are failing

### ISSUE THREAD

**Issue by xFran** [freme-project/e-services#26] opened 2016-07-28 17:09 UTC
``` 

curl -X POST -H "Accept: application/json" -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: 56b5c444-1f20-63f5-4a19-d41b0762df83" -d '[
    {
      "method": "POST",
      "endpoint": "http://api.freme-project.eu/current/e-entity/freme-ner/documents",
      "parameters": {
        "language": "en",
        "dataset": "dbpedia"
      },
      "headers": {
        "content-type": "text/plain",
        "accept": "text/turtle"
      },
      "body": "Dublin is great!"
    },
    {
      "method": "POST",
      "endpoint": "http://api.freme-project.eu/current/e-link/documents/",
      "parameters": {
        "templateid": "4496"
      },
      "headers": {
        "content-type": "text/turtle",
        "accept": "application/json+ld"
      }
    }
  ]' "http://api.freme-project.eu/current/pipelining/chain"

```

This command worked before and now I get this error

```
{
  "exception": "eu.freme.bservices.filter.proxy.exception.BadGatewayException",
  "path": "/e-entity/freme-ner/documents",
  "message": "Proxy failed: org.apache.http.conn.HttpHostConnectException: Connect to rv2622.1blu.de:7002 [rv2622.1blu.de/178.254.20.8] failed: Verbindungsaufbau abgelehnt",
  "error": "Bad Gateway",
  "status": 502,
  "timestamp": 1469725210805
}
```

Any idea why?

This is urgent!! We use it in production.

**Comment by jnehring** [comment] 2016-07-29 08:43
I investigate on this

**Comment by jnehring** [comment] 2016-07-29 08:46
It works now. @xFran please try again.

**Comment by xFran** [comment] 2016-07-29 08:50
It's working. Thank you @jnehring.

**Comment by jnehring** [comment] 2016-08-02 11:34
What is the problem? When I execute the CURL then I get status code 200 and json ld data so it looks fine to me.

**Comment by xFran** [comment] 2016-08-02 11:37
I just reopen this issue because we have the same problem. The servers are failing.

You said you investigated on this. What is/was the problem?

**Comment by jnehring** [comment] 2016-08-02 11:40
I opened this issue here: https://github.com/freme-project/FREMECommon/issues/22

**Comment by xFran** [comment] 2016-08-02 11:42
Ok. so I close this one and I follow https://github.com/freme-project/FREMECommon/issues/22

**Comment by xFran** [comment] 2016-08-05 23:25
The service is failing again.

"STATUS_CODE": 400,
        "CONTENT": {
            "exception": "eu.freme.common.exception.BadRequestException",
            "path": "\/pipelining\/chain",
            "message": "Request 0: java.net.UnknownHostException: api.freme-project.eu",
            "error": "Bad Request",
            "status": 400,
            "timestamp": 1470439348896
        }

**Comment by jnehring** [comment] 2016-08-08 09:11
The problem is again https://github.com/freme-project/FREMECommon/issues/22

I restarted FREME live. Is the problem solved? Can we close the issue?

**Closed** 2016-08-10 14:50 UTC
